# Linear Regression

In [14]:
# import packages
import pandas as pd
import numpy as np

## Toy Dataset

In [15]:
X = np.array([[1, 2], [4, 5], [2, 1], [5,6]])
y = np.array([0.1, 1.5, 0.2, 2])

In [16]:
test = np.array([[1, 2], [3, 3]])

## Define the linear regression class

In [17]:
class LinearRegression():
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def linear_reg(self, lam):
        '''
        Computes weights by fitting OLS. Lambda is the regularisation term 
        that handles issues arising due to non-invertible matrix X

        Inputs:
        X - Features
        y - Target
        lam - Regularisation constant

        Computes:
        W - Coefficients corresponding to every feature
        '''
        self.W = np.dot(
            np.linalg.inv(
                np.dot(self.X.T, self.X) + lam * np.identity(len(self.X[0]))), np.dot(self.X.T, self.y))
        print('Weights: ' +  str(self.W))

    def predict(self, test):
        '''
        Multiply the features of every row with the corresponding coefficients
        '''
        self.preds = []
        self.test = test
        for row in self.test:
            self.preds.append(
                np.sum([row[i] * self.W[i] for i in range(len(row))]))
        print('Predictions: ' +  str(self.preds))

In [18]:
model = LinearRegression(X, y)

In [19]:
model.X

array([[1, 2],
       [4, 5],
       [2, 1],
       [5, 6]])

In [20]:
model.y

array([0.1, 1.5, 0.2, 2. ])

In [21]:
model.linear_reg(lam=2)

Weights: [0.1362069  0.18448276]


In [22]:
model.W

array([0.1362069 , 0.18448276])

In [23]:
model.predict(test)

Predictions: [0.5051724137931037, 0.962068965517243]


In [24]:
model.preds

[0.5051724137931037, 0.962068965517243]